### ISSUE TITLE
Atmos Control Console Issue

### ISSUE THREAD

**Issue by flimango** [Karolis2011/Aurora.3#2]
I raised the pressure up to max (5000 kPa) and it instantly resets to 2000 kPa. If I am fast enough to set pressure it will work properly, but otherwise it changes back to 2000 kPa in about .5 seconds.

**Comment by flimango** [comment]
This issue persists with both input and output. It will reset to the default shortly after changing it (the selection ONLY). If you have it actually set to an output, it will remain to that, but the targeting selection will keep resetting itself.

**Comment by Karolis2011** [comment]
It would be useful to know your operating system and IE version.

**Comment by Karolis2011** [comment]
Should be resolved with current changes.
